/*Below given function can be used for generating 5,11,16 characters alphanumeric string
These functions will return the respective characters string described below */

function gen_a() //11 characters string generating function
{
    $str_a=mt_rand(111111,999999).mt_rand(11111,99999); //desired number of numeric characters strings can be generated by concatenating this string with mt_rand() function
    return generate_a($str_a);
}

function generate_a($st){
    /*Below given arrays could be used for desired upercase or lowercase alphabetic string*/
    //static $chars=array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z');
    static $chars=array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');

    for($i=0;$i<11;++$i){
        if($i<6){
            if($i%2==0||$i%3==0) //This statement is used to select the number to replaced in string
            {
                $st[$i]=$chars[val($st[$i])];  //The numeric values are being replaced by the alphabets of $chars array with the help of val() function
            }
        }
       elseif($i>6){
            if($i%2==0){
                $st[$i]=$chars[val($st[$i])];
            }
        }
    }

return $st;
}

function gen_b() //16 characters string generating function
{
    $str_b=mt_rand(11111111,99999999).mt_rand(11111111,99999999);// 16 characters string numeric string by concatenating two 8 characters numeric string
    return  generate_b($str_b);
}

function generate_b($st){
    static $chars=array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z');
    //static $chars=array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');

    for($i=0;$i<16;++$i){
        if($i<8){
            if($i%2==0||$i%3==0){
                $st[$i]=$chars[val($st[$i])];
            }
        }
       elseif($i>8){
            if($i%3==0){
                $st[$i]=$chars[val($st[$i])];
            }
        }
    }

return $st;
}


function gen_c() //5 characters string generating function
{
    $str_c=mt_rand(111,999).mt_rand(11,99);
    return generate_c($str_c);
}

function generate_c($st){
    //static $chars=array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z');
    static $chars=array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');

    for($i=0;$i<5;++$i){
        if($i<3){
            if($i%2==0||$i%3==0){
                $st[$i]=$chars[val($st[$i])];
            }
        }
       elseif($i>3){
            if($i%2==0){
                $st[$i]=$chars[val($st[$i])];
            }
        }
    }

return $st;
}

/*This is the main function which is acting like a mapping function, 
It return a random value in the range of 1-25 which determines the number in the string should be replaced by which character
*/
function val($vl) 
{
    $vl%=6;
    $vl*=mt_rand(1,5);
    return $vl;
}

?>
